db.estudiantes.insertOne(
	{materia: "Diseño de Sistemas", 
	 curso: "K3052", 
	 alumno:   
	 	{ nombreApellido: "Vojnov, Florencia", 
	 	  parciales: [ { parcial: { fecha: "27/07/2013", nota: "4"} } ] 
	 	} 
	 })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Estrada, Felipe", parciales: [ { parcial: { fecha: "27/07/2013", nota: "N/A" } } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Ferrari, Pablo Nahuel", parciales: [ { parcial: { fecha: "27/07/2013", nota: "N/A"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Zelayeta, Julián", parciales: [ { parcial: { fecha: "27/07/2013", nota: "N/A"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Castelnovo, Lucas", parciales: [ { parcial: { fecha: "27/07/2013", nota: "6"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Hodes, Agustín", parciales: [ { parcial: { fecha: "27/07/2013", nota: "Ausente"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Schvartz, Guillermo", parciales: [ { parcial: { fecha: "27/07/2013", nota: "3"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Romero, Martín", parciales: [ { parcial: { fecha: "27/07/2013", nota: "4"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Cestari, Ariel", parciales: [ { parcial: { fecha: "27/07/2013", nota: "2"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Palumbo, Nahuel", parciales: [ { parcial: { fecha: "27/07/2013", nota: "9"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Pietrolati, Flavio", parciales: [ { parcial: { fecha: "27/07/2013", nota: "4"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Poschenrieder, Alexander", parciales: [ { parcial: { fecha: "27/07/2013", nota: "8"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Coro, Guillermo", parciales: [ { parcial: { fecha: "27/07/2013", nota: "7"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Fang, David", parciales: [ { parcial: { fecha: "27/07/2013", nota: "5"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Plá, Sebastian", parciales: [ { parcial: { fecha: "27/07/2013", nota: "8"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Toledo, Sebastian", parciales: [ { parcial: { fecha: "27/07/2013", nota: "7"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Casaubon, Javier", parciales: [ { parcial: { fecha: "27/07/2013", nota: "Ausente"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Branda, Nahuel", parciales: [ { parcial: { fecha: "27/07/2013", nota: "5"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Garcia, Diego", parciales: [ { parcial: { fecha: "27/07/2013", nota: "Ausente"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Clausi, Laureano", parciales: [ { parcial: { fecha: "27/07/2013", nota: "8"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "De los Santos, Martin Ariel", parciales: [ { parcial: { fecha: "27/07/2013", nota: "7"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Furman, Kevin", parciales: [ { parcial: { fecha: "27/07/2013", nota: "3"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "García, Cristian", parciales: [ { parcial: { fecha: "27/07/2013", nota: "9"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Grillo, Guillermo", parciales: [ { parcial: { fecha: "27/07/2013", nota: "7"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Montes de Oca, Francisco", parciales: [ { parcial: { fecha: "27/07/2013", nota: "5"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Morales, Matías", parciales: [ { parcial: { fecha: "27/07/2013", nota: "7"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Ramos, Andrea", parciales: [ { parcial: { fecha: "27/07/2013", nota: "2"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Bravo, Sebastian", parciales: [ { parcial: { fecha: "27/07/2013", nota: "5"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Franchino, Gonzalo", parciales: [ { parcial: { fecha: "27/07/2013", nota: "2"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Mallo, Emiliano", parciales: [ { parcial: { fecha: "27/07/2013", nota: "8"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Pantano, Fiamma", parciales: [ { parcial: { fecha: "27/07/2013", nota: "9"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "García, Franco", parciales: [ { parcial: { fecha: "27/07/2013", nota: "7"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Moll, Matias", parciales: [ { parcial: { fecha: "27/07/2013", nota: "9"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "García, Leandro Gabriel", parciales: [ { parcial: { fecha: "27/07/2013", nota: "7"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Sorella, Javier", parciales: [ { parcial: { fecha: "27/07/2013", nota: "9"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "La Ferraro, Matías", parciales: [ { parcial: { fecha: "27/07/2013", nota: "2"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Noya, Diego", parciales: [ { parcial: { fecha: "27/07/2013", nota: "6"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Vallone, Matías", parciales: [ { parcial: { fecha: "27/07/2013", nota: "4"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Gimbatti, Christian", parciales: [ { parcial: { fecha: "27/07/2013", nota: "6"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Grande, Leonardo", parciales: [ { parcial: { fecha: "27/07/2013", nota: "2"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Pardo, Nicolas", parciales: [ { parcial: { fecha: "27/07/2013", nota: "1"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3052", alumno:   {nombreApellido: "Pinto, Ezequiel", parciales: [ { parcial: { fecha: "27/07/2013", nota: "4"} } ] } })

db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3053", alumno:   {nombreApellido: "Eliaschev, Nicolás", parciales: [ { parcial: { fecha: "24/07/2013", nota: "8"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3053", alumno:   {nombreApellido: "Pereyra, Ariel", parciales: [ { parcial: { fecha: "24/07/2013", nota: "4"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3053", alumno:   {nombreApellido: "Saieg, Sebastian", parciales: [ { parcial: { fecha: "24/07/2013", nota: "10"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3053", alumno:   {nombreApellido: "Valente, Miguel", parciales: [ { parcial: { fecha: "24/07/2013", nota: "7"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3053", alumno:   {nombreApellido: "Delpino, Ruben", parciales: [ { parcial: { fecha: "24/07/2013", nota: "2"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3053", alumno:   {nombreApellido: "Fermepin, Andres", parciales: [ { parcial: { fecha: "24/07/2013", nota: "9"} } ] } })
db.estudiantes.insertOne({materia: "Diseño de Sistemas", curso: "K3053", alumno:   {nombreApellido: "Rocchio, Claudio", parciales: [ { parcial: { fecha: "24/07/2013", nota: "2"} }, { parcial: { fecha: "29/08/2013", nota: "9"} } ] } })