name: build-estudiantes

on: 
  push

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start MongoDB
        run: docker compose -f "docker-compose.yml" up -d --build
        
      - name: Stop containers
        if: always()
        run: docker compose -f "docker-compose.yml" down
        